# SPDX-FileCopyrightText: © 2026 Nikita Krasnov <nikita.nikita.krasnov@gmail.com>
#
# SPDX-License-Identifier: MIT

[package]
name = "kconfq"
version = "0.1.8"
authors = ["Nikita Krasnov <nikita.nikita.krasnov@gmail.com>"]
edition = "2024"
description = "A portable way to query kernel configuration on a live system"
readme = "README.md"
repository = "https://github.com/synalice/kconfq"
license = "MIT"
keywords = ["kconfig", "query", "kernel-config", "config"]
categories = ["command-line-utilities", "config", "os", "parsing"]

[features]
capi = []

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
flate2 = "1.1.5"
nix = { version = "0.30.1", features = ["feature"] }
regex = "1.12.2"
thiserror = "2.0.17"

[package.metadata.docs.rs]
all-features = true
